### ISSUE TITLE
compiling v1.20 failed but fix is easy

### ISSUE THREAD

**Issue by tissatussa** [Sazgr/peacekeeper#1]
i tried to compile your v1.20 source but it failed.
in the file `uci.h` i find this code line :

`out << "id name Peacekeeper v" << VERSION << '\n'`

here VERSION is not defined and gives an error.
i fixed it simply by adjusting that line to this :

`out << "id name Peacekeeper v1.20\n"`

this way i get a valid binary and it runs fine in CuteChess.
btw. to compile i used this command line : `g++ *.cpp -Wall -O3 -DNDEBUG -march=native -o peacekeeper_v1.20`

i guess a fix will be easy ..

[ i'm on Xubuntu 22.04 ]

**Comment by Sazgr** [comment]
Hi, `VERSION` was intended to be used as a preprocessor macro to not have to change `uci.h` on every release. (If I had to, I would surely forget.) However, I have not edited the compiling instructions in the README, and will do that right now so compiling works following instructions.
