### ISSUE TITLE
Build environment

### ISSUE THREAD

**Issue by lordlouckster** [Sazgr/peacekeeper#10]
What environment and command do you build your Windows builds with? I just can't reach the same speeds...

**Comment by Sazgr** [comment]
Hi,
I use a recent clang (I think it is 16) with the command `clang++ -fuse-ld=lld -pthread -std=c++17 -O3 -ffast-math -DNDEBUG -DNETWORK_FILE=\"src/default.nn\" -m64 -mpopcnt -msse2 -mavx2 -mavx512f -mavx512bw -mavx512dq -flto -static -o peacekeeper-avx512.exe src\*.cpp` for the AVX512 build, and remove the architecture-specific flags for the rest of the builds. Let me know if you have any other questions.

**Comment by lordlouckster** [comment]
I'm in shock how you managed to find the fastest build settings. -march=native built a noticeably slower binary for me.

**Comment by Sazgr** [comment]
That's interesting and I'm not sure why that is. I wouldn't think that -march=native would be so much slower if at all.
