### ISSUE TITLE
Segfaults on Linux

### ISSUE THREAD

**Issue by Sazgr** [Sazgr/peacekeeper#7]
Peacekeeper segfaults on Linux when compiled with Makefile, after sending `go` command. Issue is in move_order_tables.age() function.

**Comment by tissatussa** [comment]
about 3 minutes ago i `git clone`d your source and it compiles OK on Xubuntu 22.04, with `g++ v11` (default here) and even `g++-12` !? no single error or warning, i get valid 3.3 - 3.8 Mb binaries which run fine in SCID and CuteChess ..

**Comment by Sazgr** [comment]
It is a problem on some OpenBench devices.

**Comment by tissatussa** [comment]
> It is a problem on some OpenBench devices.

you discovered this due to my remark ?
can i supply my OpenBench version ? (i have no clue how .. i guess i once installed it)

**Comment by Sazgr** [comment]
No, I made this issue because I noticed it myself on the Caissa OpenBench and wanted to keep a reminder to myself.
