### ISSUE TITLE
Please add ARMv9.2, SVE2, Dot Product and Neon support

### ISSUE THREAD

**Issue by Chess321** [Sazgr/peacekeeper#8]
It's sad that it's not possible to compile the newest version on Android and Linux devices.

**Comment by Sazgr** [comment]
Hi,
Do you know what the specific problem is in the code? Thanks.

**Comment by Sazgr** [comment]
I don't believe there is a problem as the NNUE code can be run without SIMD. If you cannot compile it, reopen this issue and post your errors.
